
export const COIN_COSTS = {
  VALIDATE_FORM: 200,
  VALIDATE_PURCHASED_FORM: 120,
  ADD_RESPONSE: 2,
  AI_ANALYSIS: 10,
};

export const LIBRARY_PRICES = {
  DEFAULT_FORM_PRICE: 200,
  DEFAULT_PRICE_PER_RESPONSE: 4,
};

export const COMMISSION_RATES = {
  CREATOR_FORM_SALE: 0.6,
  CREATOR_RESPONSE_SALE: 0.5,
};