

export const COIN_COSTS = {
  VALIDATE_FORM: 500,
  VALIDATE_PURCHASED_FORM: 500,
  ADD_RESPONSE: 10,
  AI_ANALYSIS: 500,
};

export const PLATFORM_FEES = {
    MONTHLY: 50,
};

export const LIBRARY_PRICES = {
  DEFAULT_FORM_PRICE: 700,
  DEFAULT_PRICE_PER_RESPONSE: 15,
};

export const COMMISSION_RATES = {
  CREATOR_FORM_SALE: 400 / 700, // 400 coins out of 700
  CREATOR_RESPONSE_SALE: 10 / 15, // 10 coins out of 15
};